
--Query A
SELECT TO_CHAR(datetable.DATEVALUE, 'DAY') AS WEEKDAY, SUM(sale.QTY * sale.SALEPRICE) AS TOTALSALES
FROM DWSALE sale
JOIN DWDATE datetable ON sale.SALE_DWDATEID = datetable.DATEKEY
GROUP BY TO_CHAR(datetable.DATEVALUE, 'DAY')
ORDER BY TOTALSALES DESC;

/
-- Query B
SELECT cust.CUSTCATNAME AS CUSTOMER_CATEGORY, SUM(sale.QTY * sale.SALEPRICE) AS TOTALSALES
FROM DWSALE sale
JOIN DWCUST cust ON sale.DWCUSTID = cust.DWCUSTID
GROUP BY cust.CUSTCATNAME
ORDER BY TOTALSALES ASC;

/
--Query C
SELECT prod.PRODMANUNAME AS PRODMANUNAME ,SUM(sale.QTY) AS TOTALQTYSOLD
FROM DWSALE sale
JOIN DWPROD prod ON sale.DWPRODID = prod.DWPRODID
GROUP BY prod.PRODMANUNAME
ORDER BY TOTALQTYSOLD DESC;

/
--Query D
SELECT cust.DWCUSTID,cust.FIRSTNAME,cust.SURNAME,SUM(sale.QTY * sale.SALEPRICE) AS TOTALSALES
FROM DWSALE sale
JOIN DWCUST cust ON sale.DWCUSTID = cust.DWCUSTID
GROUP BY cust.DWCUSTID, cust.FIRSTNAME, cust.SURNAME
ORDER BY TOTALSALES DESC
FETCH FIRST 10 ROWS ONLY;

/
--Query E
SELECT prod.DWPRODID,prod.PRODNAME,SUM(sale.QTY) AS TOTALSALES
FROM DWSALE sale
JOIN DWPROD prod ON sale.DWPRODID = prod.DWPRODID
GROUP BY prod.DWPRODID, prod.PRODNAME
ORDER BY TOTALSALES ASC
FETCH FIRST 10 ROWS ONLY;
/
--Query F 
SELECT cust.STATE, cust.CITY, SUM(sale.QTY * sale.SALEPRICE) AS TOTALSALES
FROM DWSALE sale
JOIN DWCUST cust ON sale.DWCUSTID = cust.DWCUSTID
GROUP BY cust.STATE, cust.CITY
HAVING SUM(sale.QTY * sale.SALEPRICE) = (SELECT MAX(SUM(s2.QTY * s2.SALEPRICE))FROM DWSALE s2 JOIN DWCUST c2 ON s2.DWCUSTID = c2.DWCUSTID WHERE c2.STATE = cust.STATE GROUP BY c2.CITY)
ORDER BY cust.STATE ASC;
/

