
CREATE OR REPLACE PACKAGE CustomerPackage AS
    FUNCTION GET_ALLCUST RETURN SYS_REFCURSOR;
END CustomerPackage;
/

CREATE OR REPLACE PACKAGE ProductPackage AS
    FUNCTION GET_ALLPROD_FROM_DB RETURN SYS_REFCURSOR;
END ProductPackage;
/

CREATE OR REPLACE PACKAGE SalePackage AS
    FUNCTION GET_ALLSALES_FROM_DB RETURN SYS_REFCURSOR;
END SalePackage;
/
CREATE OR REPLACE PACKAGE BODY SalePackage AS
    FUNCTION GET_ALLSALES_FROM_DB RETURN SYS_REFCURSOR AS
        sale_cursor SYS_REFCURSOR;
    BEGIN
        OPEN sale_cursor FOR SELECT * FROM SALE;
        RETURN sale_cursor;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20000, SQLERRM);
    END GET_ALLSALES_FROM_DB;
END SalePackage;
/

CREATE OR REPLACE PACKAGE BODY CustomerPackage AS
    FUNCTION GET_ALLCUST RETURN SYS_REFCURSOR AS
        cust_cursor SYS_REFCURSOR;
    BEGIN
        OPEN cust_cursor FOR SELECT * FROM CUSTOMER;
        RETURN cust_cursor;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20000, SQLERRM);
    END GET_ALLCUST;
END CustomerPackage;
/

CREATE OR REPLACE PACKAGE BODY ProductPackage AS
    FUNCTION GET_ALLPROD_FROM_DB RETURN SYS_REFCURSOR AS
        prod_cursor SYS_REFCURSOR;
    BEGIN
        OPEN prod_cursor FOR SELECT * FROM PRODUCT;
        RETURN prod_cursor;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20000, SQLERRM);
    END GET_ALLPROD_FROM_DB;
END ProductPackage;
/
